[project]
name = "citycleaning"
version = "1.0"
requires-python = ">=3.12"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements_api.txt"]}

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"