version: 2

sources:
  - name: city_cleaning
    database: rue-de-paris-472314
    schema: city_cleaning_dev
    tables:
      - name: dmr
        description: "Données fournies par l'application Dans ma rue"
        columns:
          - name: numero
            description: "Id de la déclaration"
          - name: type
            description: "Type de l'anomalie"
          - name: soustype
            description: "Sous type de l'anomalie"
          - name: adresse
            description: "Adresse de l'anomalie"
          - name: code_postal
            description: "Code postal"
          - name: ville
            description: "Ville"
          - name: arrondissement
            description: "ARRONDISSEMENT"
          - name: conseilquartier
            description: "Conseil de quartier concerné par l'anomalie"
          - name: datedecl
            description: "Date de la déclaration"
          - name: anneedecl
            description: "Année de la déclaration"
          - name: moisdecl
            description: "Mois de la déclaration"
          - name: prefixe
            description: "Appareil déclarant l'anomalie"
          - name: intervenant
            description: "Pôle de la mairie concerné"
          - name: id_dmr
            description: "Id de l'utilisateur"
          - name: geo_shape
            description: "Coordonnées en format JSON de l'anomalie"
          - name: geo_point_2d
            description: "Coordonées de l'anomalie"
          - name: mois_annee_decla
            description: "Mois et annee de la déclaration"

      - name: colonne_verre
        description: "Poubelle pour les déchets de verre"
        columns:
          - name: arrdt
            description: "Code postal"
          - name: geo_point_2d
            description: "Coordonnées de la poubelle"
      
      - name: composteur
        description: "Poubelle pour le composte"
        columns:
          - name: arrdt
            description: "Code postal"
          - name: geo_point_2d
            description: "Coordonnées de la poubelle"
      
      - name: recyclerie
        description: "Poubelle pour les déchets ménagers recyclables"
        columns:
          - name: code_postal
            description: "Code postal"
          - name: coordonnees_geo
            description: "Coordonnées de la poubelle"
      
      - name: textile
        description: "Poubelle pour les déchets textiles"
        columns:
          - name: code_postal
            description: "Code postal"
          - name: coordonnees_geo
            description: "Coordonnées de la poubelle"
      
      - name: trilib
        description: "Poubelle Trilib"
        columns:
          - name: code_postal
            description: "Code postal"
          - name: coordonnees_geo_wgs84
            description: "Coordonnées de la poubelle"