name: 'Deploy dbt files on bucket - dev'

on:
  push:
    branches:
      - feat/dags-sync
    # paths:
      # - "dbt-dmr/models/**"

jobs:
  dbt-models:
    name: Dbt - profile and models
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS}}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: Create profiles file for dbt
        env:
          DBT_PROFILE: ${{ secrets.DBT_PROFILE}}
        run: |
          echo $DBT_PROFILE > profiles.yml
          cat profiles.yml

      - name: Deploy
        run: |
          gsutil -m rsync -R dbt-dmr/dbt_project.yml gs://city-cleaning-airflow-dev/dags/
          gsutil -m rsync -R dbt-dmr/models/ gs://city-cleaning-airflow-dev/dags/models/


